CREATE TABLE ORDERS1
(
ID INT PRIMARY KEY NOT NULL,
ORDERDATE DATETIME NOT NULL,
ORDERNUMBER NVARCHAR(10) NULL,
CUSTOMERID INT NOT NULL,
TOTALAMOUNT DECIMAL(12,2) NULL
)

CREATE TABLE ORDERITEM1
(
ID INT PRIMARY KEY NOT NULL,
ORDERID INT NOT NULL,
PRODUCTID INT NOT NULL,
UNITPRICE DECIMAL(12,2) NOT NULL,
QUANTITY INT NOT NULL
)

CREATE TABLE PRODUCT1
(
ID INT PRIMARY KEY NOT NULL,
PRODUCTNAME NVARCHAR(50) NOT NULL,
SUPPLIERID INT NOT NULL,
UNITPRICE DECIMAL(12,2) NOT NULL,
PACKAGE NVARCHAR(30) NULL,
ISDISCONTINUED BIT NULL
)

CREATE TABLE SUPPLIER1
(
ID INT PRIMARY KEY NOT NULL,
COMPANYNAME NVARCHAR(40) NOT NULL,
CONTACTNAME NVARCHAR(50) NULL,
CONTACTTITLE NVARCHAR(40) NULL,
CITY NVARCHAR(40) NULL,
COUNTRY NVARCHAR(40) NULL,
PHONE NVARCHAR(20) NULL,
FAX NVARCHAR(30) NULL
)

CREATE TABLE ÝTEMSPECÝFÝCS1
(
ID INT PRIMARY KEY NOT NULL,
HEIGHT INT NOT NULL,
WIDTH INT NOT NULL,
WEIGHT INT NOT NULL,
LENGTH INT NOT NULL,
)
