create table UCAK(
UCAK_NO NUMERIC NOT NULL,
UCAK_ADI VARCHAR(30) UNIQUE,
UCAK_TIPI VARCHAR(1) DEFAULT 'J',
MOTOR_GUCU NUMERIC,
URETIM_TARIHI DATE,
CONSTRAINT UCAK_TIPI CHECK(UCAK_TIPI IN('J','P'))
);