CREATE TABLE CLIENT_MASTER(
client_no VARCHAR(25) PRIMARY KEY,
"NAME" VARCHAR(20),
ADDRESS1 VARCHAR(30),
ADDRESS2 VARCHAR(30),
CITY VARCHAR(15),
"STATE" VARCHAR(15),
PINCODE NUMERIC(6),
bal_due NUMERIC(10,2));

CREATE TABLE PRODUCT_MASTER(
Product_no VARCHAR(6) PRIMARY KEY,
"Description" VARCHAR(30),
Profit_percent NUMERIC,
Unit_measure VARCHAR(10),
Qty_on_hand NUMERIC,
Reoder_lvl NUMERIC,
Sell_price NUMERIC,
Cost_price NUMERIC)

CREATE TABLE SALESMAN_MASTER(
SALESMAN_NO VARCHAR(6) PRIMARY KEY check(SALESMAN_NO Like '5%'),
SALESMANNAME VARCHAR(20) NOT NULL,
"ADDRESS" VARCHAR(30) NOT NULL,
CITY VARCHAR(20),
PINCODE NUMERIC(6),
"STATE" VARCHAR(20),
SALAMT NUMERIC(8,2) NOT NULL,
TGT_TO_GET NUMERIC(6,2) NOT NULL,
YTD_SALES NUMERIC(6,2) NOT NULL,
REMARKS VARCHAR(30));

CREATE TABLE SALES_ORDER(
S_order_no VARCHAR(6) PRIMARY KEY,
client_no VARCHAR(25) REFERENCES CLIENT_MASTER,
S_order_date DATE,
SALESMAN_NO VARCHAR(6) REFERENCES SALESMAN_MASTER,
DELY_TYPE VARCHAR(1) DEFAULT 'F',
BILLED_YN VARCHAR(1),
DELY_DATE DATE,
ORDERSTATUS VARCHAR(10),
CONSTRAINT CK_DELIVTYPE CHECK(DELY_TYPE IN('P','F')),
CONSTRAINT CK_DELIVDATE CHECK(DELY_DATE > S_order_date),
CONSTRAINT CK_ORDERSTATUS CHECK(ORDERSTATUS IN('In Process','Fulfilled','Backorder','Cancelled')));

CREATE TABLE SALES_ORDER_DETAILS(
S_order_no VARCHAR(6) REFERENCES SALES_ORDER,
Product_no VARCHAR(6) REFERENCES PRODUCT_MASTER,
QTYORDERED NUMERIC(8),
QTYDISP NUMERIC(8),
PRODUCTRATE NUMERIC(10,2));